### ISSUE TITLE
Windows machine its not working

### ISSUE THREAD

**Issue by kumkanillam** [josa42/vscode-ember-related-files#9]
I tried even after disabling and enabling but its not openning the related files when I click `Ctrl + Alt + r`.  I think It was working well earlier.  not sure about the reason. I upgraded nodejs to node-v8.1.2-x64.  is this relevant?.

**Comment by enkol** [comment]
Possibly a file seperator issue again (see #6). 

I'll look at it this weekend and fill a PR if i find a fix.

**Comment by enkol** [comment]
There was indeed a file path issue within workspace folder detection on Windows. I submitted PR #11 with a fix.
